
class DummyData {
  static const listingDummyItems = [
    {
      "itemId": "12398nasd",
      "title": "소시지 같이 구매하실분",
      "desc": "12개에 2천원인데 혼자 사기에는 너무 많아요. 같이 구매하실분..",
      "createdAt" : "",
      "maxParticipants": 4,
      "currentParticipants": 3,
      "totalPrice" : 2000,
      "totalCount" : 12,
    },
    {
      "itemId": "12398nssd",
      "title": "소시지 같이 구매하실분",
      "desc": "12개에 2천원인데 혼자 사기에는 너무 많아요. 같이 구매하실분..",
      "createdAt" : "",
      "maxParticipants": 4,
      "currentParticipants": 3,
      "totalPrice" : 2000,
      "totalCount" : 12,
    },
    {
      "itemId": "12398nsszxcd",
      "title": "소시지 같이 구매하실분",
      "desc": "12개에 2천원인데 혼자 사기에는 너무 많아요. 같이 구매하실분..",
      "createdAt" : "",
      "maxParticipants": 4,
      "currentParticipants": 3,
      "totalPrice" : 2000,
      "totalCount" : 12,
    },
    {
      "itemId": "12398nasfassd",
      "title": "소시지 같이 구매하실분",
      "desc": "12개에 2천원인데 혼자 사기에는 너무 많아요. 같이 구매하실분..",
      "createdAt" : "",
      "maxParticipants": 4,
      "currentParticipants": 3,
      "totalPrice" : 2000,
      "totalCount" : 12,
    },
    {
      "itemId": "12398nasdsd",
      "title": "소시지 같이 구매하실분",
      "desc": "12개에 2천원인데 혼자 사기에는 너무 많아요. 같이 구매하실분..",
      "createdAt" : "",
      "maxParticipants": 4,
      "currentParticipants": 3,
      "totalPrice" : 2000,
      "totalCount" : 12,
    },
    {
      "itemId": "12398nasdsd",
      "title": "소시지 같이 구매하실분",
      "desc": "12개에 2천원인데 혼자 사기에는 너무 많아요. 같이 구매하실분..",
      "createdAt" : "",
      "maxParticipants": 4,
      "currentParticipants": 3,
      "totalPrice" : 2000,
      "totalCount" : 12,
    },
  ];

}
